// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0uGiL893PXFeS3DbfRX5c_J4GIIRAkNE',
    appId: '1:1031283211350:web:33249fa8fad288a36e0ff7',
    messagingSenderId: '1031283211350',
    projectId: 'cs8803-sample-app',
    authDomain: 'cs8803-sample-app.firebaseapp.com',
    storageBucket: 'cs8803-sample-app.firebasestorage.app',
    measurementId: 'G-6MEYPYJD75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfsX6xovM8t614C_zO8CH_v6bj6FImvvY',
    appId: '1:1031283211350:android:4d50518f613a08b86e0ff7',
    messagingSenderId: '1031283211350',
    projectId: 'cs8803-sample-app',
    storageBucket: 'cs8803-sample-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA63hl9z9kqG0gebxm8GKzDWi4YHcT65uY',
    appId: '1:1031283211350:ios:22acf4909b142f616e0ff7',
    messagingSenderId: '1031283211350',
    projectId: 'cs8803-sample-app',
    storageBucket: 'cs8803-sample-app.firebasestorage.app',
    iosBundleId: 'com.example.sampleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0uGiL893PXFeS3DbfRX5c_J4GIIRAkNE',
    appId: '1:1031283211350:web:5477400e5d080bf66e0ff7',
    messagingSenderId: '1031283211350',
    projectId: 'cs8803-sample-app',
    authDomain: 'cs8803-sample-app.firebaseapp.com',
    storageBucket: 'cs8803-sample-app.firebasestorage.app',
    measurementId: 'G-9C6KCRT0Y1',
  );
}
